"""Second migration

Revision ID: 79ae9174fc00
Revises: 3f56fd0636ab
Create Date: 2020-02-10 01:32:55.243430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ae9174fc00'
down_revision = '3f56fd0636ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_listings', sa.Column('notes', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_listings', 'notes')
    # ### end Alembic commands ###
