"""empty message

Revision ID: f8f3563e604e
Revises: 
Create Date: 2018-12-01 15:32:13.298139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f3563e604e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airlines', sa.String(length=20), nullable=True),
    sa.Column('flight_no', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('seatcount', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('hname', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('hprice', sa.Integer(), nullable=True),
    sa.Column('fromdate', sa.DateTime(), nullable=True),
    sa.Column('todate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=10), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=True),
    sa.Column('lastname', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.Column('phoneno', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('ordernumber', sa.String(length=30), nullable=True),
    sa.Column('card_type', sa.String(length=10), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('cvv_no', sa.String(length=3), nullable=True),
    sa.Column('card_name', sa.String(length=30), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('total_persons', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_listings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_listings.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('c_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonals')
    op.drop_table('persons')
    op.drop_table('order_history')
    op.drop_table('users')
    op.drop_table('promocode')
    op.drop_table('hotel_listings')
    op.drop_table('flight_listings')
    # ### end Alembic commands ###
